name: dir_splitter
description: Split large directories into parts of a specified maximum size.
version: 1.0.0
repository: https://github.com/jinyus/dir_splitter

environment:
    sdk: ^3.0.6

dependencies:
    args: ^2.4.2
    file: ^7.0.0
    glob: ^2.1.2
    path: ^1.8.3

dev_dependencies:
    lints: ^2.0.0
    test: ^1.21.0
    build_version: ^2.1.1
    build_runner: ^2.4.6
